"""
Pynguin-generated tests for auth.py module.
Search-based test generation focusing on branch coverage.
"""
import pytest
from flask import Flask
from werkzeug.security import generate_password_hash

from flaskr import create_app
from flaskr.db import get_db, init_db
import tempfile
import os


@pytest.fixture
def app():
    """Create and configure a new app instance for each test."""
    db_fd, db_path = tempfile.mkstemp()
    app = create_app({"TESTING": True, "DATABASE": db_path})
    
    with app.app_context():
        init_db()
    
    yield app
    
    os.close(db_fd)
    os.unlink(db_path)


@pytest.fixture
def client(app):
    """A test client for the app."""
    return app.test_client()


class TestLoginRequired:
    """Pynguin-generated tests for login_required decorator."""
    
    def test_case_1(self, app, client):
        """Test case generated by Pynguin - anonymous access."""
        response = client.get("/create")
        assert response.status_code == 302
    
    def test_case_2(self, app, client):
        """Test case generated by Pynguin - logged in access."""
        # Create user and login
        with app.app_context():
            db = get_db()
            db.execute(
                "INSERT INTO user (username, password) VALUES (?, ?)",
                ("user1", generate_password_hash("pass1"))
            )
            db.commit()
        
        client.post("/auth/login", data={"username": "user1", "password": "pass1"})
        response = client.get("/create")
        assert response.status_code in [200, 302]


class TestLoadLoggedInUser:
    """Pynguin-generated tests for load_logged_in_user."""
    
    def test_case_3(self, app, client):
        """Test case - no session."""
        response = client.get("/")
        assert response.status_code == 200
    
    def test_case_4(self, app, client):
        """Test case - with session."""
        with app.app_context():
            db = get_db()
            db.execute(
                "INSERT INTO user (username, password) VALUES (?, ?)",
                ("user2", generate_password_hash("pass2"))
            )
            db.commit()
        
        with client.session_transaction() as sess:
            sess["user_id"] = 1
        
        response = client.get("/")
        assert response.status_code == 200


class TestRegister:
    """Pynguin-generated tests for register route."""
    
    def test_case_5(self, client):
        """Test case - GET request."""
        response = client.get("/auth/register")
        assert response.status_code == 200
    
    def test_case_6(self, client):
        """Test case - POST with empty username."""
        response = client.post(
            "/auth/register",
            data={"username": "", "password": "pass123"}
        )
        assert response.status_code == 200
    
    def test_case_7(self, client):
        """Test case - POST with empty password."""
        response = client.post(
            "/auth/register",
            data={"username": "newuser", "password": ""}
        )
        assert response.status_code == 200
    
    def test_case_8(self, client, app):
        """Test case - successful registration."""
        response = client.post(
            "/auth/register",
            data={"username": "newuser", "password": "newpass"}
        )
        assert response.status_code == 302
    
    def test_case_9(self, client, app):
        """Test case - duplicate username."""
        # Register first time
        client.post(
            "/auth/register",
            data={"username": "duplicate", "password": "pass1"}
        )
        
        # Try to register again
        response = client.post(
            "/auth/register",
            data={"username": "duplicate", "password": "pass2"}
        )
        assert response.status_code == 200


class TestLogin:
    """Pynguin-generated tests for login route."""
    
    def test_case_10(self, client):
        """Test case - GET request."""
        response = client.get("/auth/login")
        assert response.status_code == 200
    
    def test_case_11(self, client, app):
        """Test case - successful login."""
        # Create user
        with app.app_context():
            db = get_db()
            db.execute(
                "INSERT INTO user (username, password) VALUES (?, ?)",
                ("loginuser", generate_password_hash("loginpass"))
            )
            db.commit()
        
        response = client.post(
            "/auth/login",
            data={"username": "loginuser", "password": "loginpass"}
        )
        assert response.status_code == 302
    
    def test_case_12(self, client, app):
        """Test case - incorrect username."""
        response = client.post(
            "/auth/login",
            data={"username": "nonexistent", "password": "pass"}
        )
        assert response.status_code == 200
    
    def test_case_13(self, client, app):
        """Test case - incorrect password."""
        # Create user
        with app.app_context():
            db = get_db()
            db.execute(
                "INSERT INTO user (username, password) VALUES (?, ?)",
                ("user3", generate_password_hash("correctpass"))
            )
            db.commit()
        
        response = client.post(
            "/auth/login",
            data={"username": "user3", "password": "wrongpass"}
        )
        assert response.status_code == 200


class TestLogout:
    """Pynguin-generated tests for logout route."""
    
    def test_case_14(self, client):
        """Test case - logout without login."""
        response = client.get("/auth/logout")
        assert response.status_code == 302
    
    def test_case_15(self, client, app):
        """Test case - logout after login."""
        # Create and login user
        with app.app_context():
            db = get_db()
            db.execute(
                "INSERT INTO user (username, password) VALUES (?, ?)",
                ("logoutuser", generate_password_hash("logoutpass"))
            )
            db.commit()
        
        client.post(
            "/auth/login",
            data={"username": "logoutuser", "password": "logoutpass"}
        )
        
        response = client.get("/auth/logout")
        assert response.status_code == 302

